name: Deploy Jekyll site to Pages and deploy branch

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write  # Allows pushing to your repository
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Push built site to 'deploy' branch
        run: |
          # Navigate to the built site directory
          cd _site

          # Configure Git user details
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          # Fetch the 'deploy' branch from the remote
          git fetch origin deploy
      
          # Check out the 'deploy' branch from the remote
          git checkout deploy
      
          # Add and commit changes
          git add .
          git commit -m "Deploy built site to 'deploy' branch"

          # Force push to the 'deploy' branch
          git push --force "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:deploy

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
